name: Auto-generate PR using Aider
on:
  issues:
    types: [labeled]

jobs:
  generate:
    uses: ./.github/workflows/aider-issue.yml
    if: github.event.label.name == 'aider'
    permissions:
      issues: read
      pull-requests: write
      contents: write
    with:
      issue-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.repository.default_branch }}
      model: openrouter/anthropic/claude-3.5-sonnet
    secrets: 
      openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
