name: Aider PR Comment Handler
on:
  issue_comment:
    types: [created]

jobs:
  process-comment:
    # Проверяем что это комментарий в PR и содержит @aider
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@aider') }}
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get PR details
        uses: actions/github-script@v7
        id: get_pr
        with:
          script: |
            const { repo, owner } = context.repo;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.issue.number
            });
            return { 
              branch: pr.data.head.ref,
              comment: '${{ github.event.comment.body }}'.replace('@aider', '').trim()
            };

      - name: Apply changes with Aider
        uses: mirrajabi/aider-github-action@main
        with:
          branch: ${{ fromJson(steps.get_pr.outputs.result).branch }}
          model: openrouter/anthropic/claude-3.5-sonnet
          aider_args: '--chat-mode architect --yes --message "${{ fromJson(steps.get_pr.outputs.result).comment }}"'
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Upload aider chat history
        uses: actions/upload-artifact@v3
        with:
          name: aider-pr-comment-chat-output
          path: ".aider.chat.history.md"

      - name: Add comment about changes
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: context.issue.number,
              body: 'Changes requested in the comment have been applied. Please review the new commit.'
            });
